### ISSUE TITLE
Crash when confirm invite from Skype group

### ISSUE THREAD

**Issue by thehijacker** [kelaresg/go-skype-bridge#20]
Hello,

I finaly made this run. Login works and says it was a success. I see lots of contacts showing. When I accept invite from one I get following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87aa8a]

goroutine 584 [running]:
maunium.net/go/mautrix/appservice.(*IntentAPI).EnsureJoined(0x0, {0xc00037e3f0, 0x24})
        /go/pkg/mod/github.com/pidongqianqian/mautrix-go@v0.10.4-0.20211208080648-321c4f849adb/appservice/intent.go:70 +0x2a
maunium.net/go/mautrix/appservice.(*IntentAPI).RedactEvent(0x0, {0xc00037e3f0, 0x24}, {0xc00037e3c0, 0x2c}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/pidongqianqian/mautrix-go@v0.10.4-0.20211208080648-321c4f849adb/appservice/intent.go:226 +0x4b
main.(*MatrixHandler).HandleMessage.func1()
        /build/matrix.go:405 +0x88
created by main.(*MatrixHandler).HandleMessage
        /build/matrix.go:402 +0x2ec
```

I have to login again.

Thank you.

**Comment by thehijacker** [comment]
Maybe important information. I have build the docker image and pushed it to dockerhub (private). Maybe something is wrong with the build? I got no error or warning messages.

**Comment by matevy** [comment]
exactly the same issue here, we thought it is because we are running it on ppc64le, but apparently not.

**Comment by CyberAdmin97** [comment]
did you find the solution ?

**Comment by matevy** [comment]
hi,

we had no time so far to search for solutions.
