### ISSUE TITLE
Segmentation violation on `HandleMessage`

### ISSUE THREAD

**Issue by forthommel** [kelaresg/go-skype-bridge#26]
Dear developers,

First, let me thank you a lot for this bridge! It has been very useful so far.

However, I am encountering issues at bridge startup (as if the user/password storage in DB introduced in https://github.com/kelaresg/go-skype-bridge/pull/14 does not work properly): I need to manually regenerate the connection token.
Furthermore, after an umpteenth of these (where all latest conversation pop up all at once in a fantastic notifications firework) it looks like the first messages display in a conversation is unevitably leading to this segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87a7ea]

goroutine 285 [running]:
maunium.net/go/mautrix/appservice.(*IntentAPI).EnsureJoined(0x0, {0xc000029f50, 0x27})
	/opt/go-skype-bridge/go/pkg/mod/github.com/pidongqianqian/mautrix-go@v0.10.4-0.20211208080648-321c4f849adb/appservice/intent.go:70 +0x2a
maunium.net/go/mautrix/appservice.(*IntentAPI).RedactEvent(0x0, {0xc000029f50, 0x27}, {0xc000029f20, 0x2c}, {0x0, 0x0, 0x0})
	/opt/go-skype-bridge/go/pkg/mod/github.com/pidongqianqian/mautrix-go@v0.10.4-0.20211208080648-321c4f849adb/appservice/intent.go:226 +0x4b
main.(*MatrixHandler).HandleMessage.func1()
	/opt/go-skype-bridge/matrix.go:405 +0x88
created by main.(*MatrixHandler).HandleMessage
	/opt/go-skype-bridge/matrix.go:402 +0x2ec
```

Could you please have a look and see if something requires a bit more attention?

Thanks in advance!
L.F.

**Comment by czen** [comment]
Encountered the same issue. Bridge synced a lot of personal and group chats, then crashed with this errror. Every restart and login now leads to the same error.

**Comment by forthommel** [comment]
Same for me, and as no update was made on this ticket I completely (and sadly) dropped this solution.

**Comment by aostanin** [comment]
I encountered this same issue and was able to work around it by removing these lines from `matrix.go`:

https://github.com/kelaresg/go-skype-bridge/blob/59e27903cd6888399706ec5b7b1757411834990c/matrix.go#L401-L410

The bot waits for 10 seconds after login then tries to remove the login message with your username and password from the chat history. That's where the crash occurs. I don't know the root cause, but at least this workaround makes the bridge usable.
