### ISSUE TITLE
Login do not persist

### ISSUE THREAD

**Issue by arkadym** [kelaresg/go-skype-bridge#28]
For me it is quite different, i can login into my skype accounts and even able send/rx couple message before it auto logout... Doesnt matter is there any activity from my side or not, result will be same, after about 1 min - session is off.
![image](https://user-images.githubusercontent.com/7422012/225000699-442b4ff6-8992-4f25-be15-0260fbc7bf19.png)

**Comment by agalbulescu** [comment]
I encounter the same issue, upon investigation I found that data is not being written in the database at all, namely the user upon login, the errors I see are the following (logs below):

**logs of the postgres db container**

```
2024-02-08 15:09:21.007 UTC [1] LOG:  database system is ready to accept connections
2024-02-08 15:11:09.681 UTC [33] ERROR:  value too long for type character varying(1500)
2024-02-08 15:11:09.681 UTC [33] STATEMENT:  UPDATE "user" SET jid=$1, management_room=$2, last_connection=$3, endpoint_id=$4, skype_token=$5, registration_token=$6, registration_token_str=$7, location_host=$8 WHERE mxid=$9
2024-02-08 15:11:10.164 UTC [33] ERROR:  insert or update on table "user_portal" violates foreign key constraint "user_portal_user_jid_fkey"
2024-02-08 15:11:10.164 UTC [33] DETAIL:  Key (user_jid)=(8:agalbulescu) is not present in table "user".
2024-02-08 15:11:10.164 UTC [33] STATEMENT:  INSERT INTO user_portal (user_jid, portal_jid, portal_receiver, in_community) VALUES ($1, $2, $3, $4), ($5, $6, $7, $8)
```

I will also try to set it up with a sqlite3 db to see if it makes a difference, but I suspect not...

**Comment by agalbulescu** [comment]
**update**: I also tried configuring a new bridge container using **sqlite3** and it seems to work, it successfully connects, syncs contacts and conversations properly, it writes in the DB all the information, _however_, afterwards it still fails throwing this error in the logs and then reboots the bridge thus disconnecting me:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87aa8a]
goroutine 163 [running]:
maunium.net/go/mautrix/appservice.(*IntentAPI).EnsureJoined(0x0, {0xc0003a2ed0, 0x23})
	/go/pkg/mod/github.com/pidongqianqian/mautrix-go@v0.10.4-0.20211208080648-321c4f849adb/appservice/intent.go:70 +0x2a
maunium.net/go/mautrix/appservice.(*IntentAPI).RedactEvent(0x0, {0xc0003a2ed0, 0x23}, {0xc0003a2ea0, 0x2c}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/pidongqianqian/mautrix-go@v0.10.4-0.20211208080648-321c4f849adb/appservice/intent.go:226 +0x4b
main.(*MatrixHandler).HandleMessage.func1()
	/build/matrix.go:405 +0x88
created by main.(*MatrixHandler).HandleMessage
	/build/matrix.go:402 +0x2ec
```

any ideas would be greatly appreciated, thanks!

**Comment by agalbulescu** [comment]
**update 2**: I found the issue, it was caused by this commit (https://github.com/kelaresg/go-skype-bridge/commit/e8af9ce34f9873d4e6362446c8f3ae0cc3cceae1), so I created a new repo/docker image for a working version of the bridge that I will try my best to keep updated:

https://hub.docker.com/r/agalbulescu/go-skype-bridge
